ecognome/druids/urls.py
from django.conf.urls import re_path

from . import views

app_name = 'druids'
urlpatterns = [

    # GT economia

    ## Estadísticas

    re_path(
        r'^gt-economia/estadisticas/reportes_mensuales_por_tipo/(?P<pk>\d+)/',
        views.ReporteMensualPorTipoDetailView.as_view(),
        name="reporte-mensual-por-tipo",
    ),

    re_path(
        r'^gt-economia/estadisticas/reportes_mensuales_por_tipo/',
        views.reportes_mensuales_por_tipo,
        name="reportes-mensuales-por-tipo",
    ),
    
    ## Cuotas
    re_path(r'^gt-economia/cuotas/mantenimiento/crear/',
        views.CuotaMantenimientoCreateView.as_view(),
        name="crear-mantenimiento"
        ),
    re_path(
        r'^gt-economia/cuotas/mantenimiento/(?P<pk>\d+)/',
        views.CuotaMantenimientoUpdateView.as_view(),
        name="desactivar-mantenimiento",
    ),
    re_path(r'^gt-economia/cuotas/mantenimiento/',
        views.CuotaMantenimientoListView.as_view(),
        name="lista-mantenimiento"
        ),
    re_path(r'^gt-economia/cuotas/piso/crear/',
        views.CuotaPisoCreateView.as_view(),
        name="crear-cuota-piso"
        ),
    re_path(r'^gt-economia/cuotas/piso/',
        views.CuotaPisoListView.as_view(),
        name="lista-cuotas-piso"
        ),
    
    ## Espacios
    re_path(r'^gt-economia/espacios/pisos/crear/',
        views.PisoCreateView.as_view(),
        name="crear-piso"
        ),
    re_path(r'^gt-economia/espacios/pisos/(?P<pk>\d+)/',
        views.PisoUpdateView.as_view(),
        name="editar-piso"
        ),
    re_path(r'^gt-economia/espacios/pisos/',
        views.PisoListView.as_view(),
        name="lista-pisos"
        ),
    re_path(r'^gt-economia/espacios/trasteros/crear/',
        views.TrasteroCreateView.as_view(),
        name="crear-trastero"
        ),
    re_path(r'^gt-economia/espacios/trasteros/(?P<pk>\d+)/',
        views.TrasteroUpdateView.as_view(),
        name="editar-trastero"
        ),
    re_path(r'^gt-economia/espacios/trasteros/',
        views.TrasteroListView.as_view(),
        name="lista-trasteros"
        ),

    ## Cuadernos Contables
    re_path(r'^gt-economia/cuadernos/entradas/(?P<tipo_entrada>\w+)',
        views.cuaderno_contable_entradas,
        name="cuaderno_contable_entradas",
        ),
    re_path(r'^gt-economia/cuadernos/entradas',
        views.cuaderno_contable_entradas,
        name="cuaderno_contable_entradas",
        ),
    re_path(r'^gt-economia/cuadernos/salidas/(?P<tipo_salida>\w+)',
        views.cuaderno_contable_salidas,
        name="cuaderno_contable_salidas",
        ),
    re_path(r'^gt-economia/cuadernos/salidas',
        views.cuaderno_contable_salidas,
        name="cuaderno_contable_salidas",
        ),
    
    ## Registros
    re_path(r'^gt-economia/registros/metalico/crear/',
        views.MetalicoCreateView.as_view(),
        name="crear-metalico"
        ),
    re_path(r'^gt-economia/registros/metalico/',
        views.MetalicoListView.as_view(),
        name="lista-metalicos"
        ),
    re_path(r'^gt-economia/registros/banco/crear/',
        views.BancoCreateView.as_view(),
        name="crear-banco"
        ),
    re_path(r'^gt-economia/registros/banco/',
        views.BancoListView.as_view(),
        name="lista-bancos"
        ),
    re_path(r'^gt-economia/registros/electronico/crear/',
        views.PaypalCreateView.as_view(),
        name="crear-paypal"
        ),
    re_path(r'^gt-economia/registros/electronico/',
        views.PaypalListView.as_view(),
        name="lista-paypals"
        ),
    re_path(r'^gt-economia/registros/extracto/(?P<registro_id>\d+)/',
        views.extracto_registro,
        name="extracto-registro"
        ),
    re_path(r'^gt-economia/registros/extracto/rectificar_salida/(?P<salida_id>\d+)/',
        views.rectificar_salida,
        name="rectificar-salida"
        ),
    re_path(r'^gt-economia/registros/extracto/rectificar_entrada/(?P<entrada_id>\d+)/',
        views.rectificar_entrada,
        name="rectificar-entrada"
        ),
    
    ## Proyectos
    re_path(r'^gt-economia/proyectos/crear/',
        views.ProyectoProductivoCreateView.as_view(),
        name="crear-proyecto"
        ),
    re_path(r'^gt-economia/proyectos/(?P<pk>\d+)/',
        views.ProyectoProductivoUpdateView.as_view(),
        name="editar-proyecto"
        ),
    re_path(r'^gt-economia/proyectos/',
        views.ProyectoProductivoListView.as_view(),
        name="lista-proyectos"
        ),

    ## Personas
    re_path(r'^gt-economia/personas/habitantes/crear/',
        views.HabitanteCreateView.as_view(),
        name="crear-habitante"
        ),
    re_path(r'^gt-economia/personas/habitantes/(?P<pk>\d+)/',
        views.HabitanteUpdateView.as_view(),
        name="editar-habitante"
        ),
    re_path(r'^gt-economia/personas/habitantes/',
        views.HabitanteListView.as_view(),
        name="lista-habitantes"
        ),
    re_path(r'^gt-economia/personas/invitadas/crear/',
        views.InvitadaCreateView.as_view(),
        name="crear-invitada"
        ),
    re_path(r'^gt-economia/personas/invitadas/(?P<pk>\d+)/',
        views.InvitadaUpdateView.as_view(),
        name="editar-invitada"
        ),
    re_path(r'^gt-economia/personas/invitadas/',
        views.InvitadaListView.as_view(),
        name="lista-invitadas"
        ),
    re_path(r'^gt-economia/personas/huespedes/crear/',
        views.HuespedCreateView.as_view(),
        name="crear-huesped"
        ),
    re_path(r'^gt-economia/personas/huespedes/(?P<pk>\d+)/',
        views.HuespedUpdateView.as_view(),
        name="editar-huesped"
        ),
    re_path(r'^gt-economia/personas/huespedes/',
        views.HuespedListView.as_view(),
        name="lista-huespedes"
        ),

    ## Pactos
    re_path(r'^gt-economia/pactos/habitantepiso/crear/',
        views.HabitantePisoCreateView.as_view(),
        name="crear-habitantepiso"
        ),
    re_path(r'^gt-economia/pactos/habitantepiso/(?P<pk>\d+)/',
        views.HabitantePisoUpdateView.as_view(),
        name="editar-habitantepiso"
        ),
    re_path(r'^gt-economia/pactos/habitantepiso/',
        views.HabitantePisoListView.as_view(),
        name="lista-habitantepiso"
        ),
    re_path(r'^gt-economia/pactos/personatrastero/crear/',
        views.PersonaTrasteroCreateView.as_view(),
        name="crear-personatrastero"
        ),
    re_path(r'^gt-economia/pactos/personatrastero/(?P<pk>\d+)/',
        views.PersonaTrasteroUpdateView.as_view(),
        name="editar-personatrastero"
        ),
    re_path(r'^gt-economia/pactos/personatrastero/',
        views.PersonaTrasteroListView.as_view(),
        name="lista-personatrastero"
        ),

    ## Movimientos
    re_path(r'^gt-economia/movimientos/salidas/crear/',
        views.insertar_salidas,
        name="crear-salida"
        ),
    re_path(r'^gt-economia/movimientos/entradas/otras/crear/',
        views.insertar_entradas_otras,
        name="crear-otras-entradas"
        ),
    re_path(r'^gt-economia/movimientos/entradas/alquileres/crear/',
        views.insertar_entradas_alquileres,
        name="crear-alquileres-entradas"
        ),
    re_path(r'^gt-economia/movimientos/entradas/proyectos/crear/',
        views.insertar_entradas_proyectos,
        name="crear-proyectos-entradas"
        ),

    ## Balances
    re_path(r'^gt-economia/balances/crear/',
        views.BalanceCreateView.as_view(),
        name="crear-balance"
        ),
    re_path(r'^gt-economia/balances/(?P<pk>\d+)/',
        views.BalanceDetailView.as_view(),
        name="ver-balance"
        ),
    re_path(r'^gt-economia/balances/',
        views.BalanceListView.as_view(),
        name="lista-balances"
        ),

    ## Export CSV

    re_path(r'^gt-economia/csv/entradas/$',
        views.exportar_entradas_csv,
        name="exportar_entradas_csv",
        ),
    re_path(r'^gt-economia/csv/salidas/$',
        views.exportar_salidas_csv,
        name="exportar_salidas_csv",
        ),
    re_path(r'^gt-economia/csv/pisos/$',
        views.exportar_pisos_csv,
        name="exportar_pisos_csv",
        ),
    re_path(r'^gt-economia/csv/trasteros/$',
        views.exportar_trasteros_csv,
        name="exportar_trasteros_csv",
        ),
    re_path(r'^gt-economia/csv/cuotas_piso/$',
        views.exportar_cuotas_piso_csv,
        name="exportar_cuotas_piso_csv",
        ),
    re_path(r'^gt-economia/csv/cuotas_mantenimiento/$',
        views.exportar_cuotas_mantenimiento_csv,
        name="exportar_cuotas_mantenimiento_csv",
        ),
    re_path(r'^gt-economia/csv/habitante_piso/$',
        views.exportar_habitante_piso_csv,
        name="exportar_habitante_piso_csv",
        ),
    re_path(r'^gt-economia/csv/persona_trastero/$',
        views.exportar_persona_trastero_csv,
        name="exportar_persona_trastero_csv",
        ),
    re_path(r'^gt-economia/csv/personas/$',
        views.exportar_personas_csv,
        name="exportar_personas_csv",
        ),
    re_path(r'^gt-economia/csv/registros/$',
        views.exportar_registros_csv,
        name="exportar_registros_csv",
        ),
    re_path(r'^gt-economia/csv/proyectos/$',
        views.exportar_proyectos_csv,
        name="exportar_proyectos_csv",
        ),
    
    ## Dashboard
    re_path(r'^gt-economia/', views.gt_dashboard, name='gt-dashboard'),

    # Public dashboard
    ## API
    re_path(r'^api/cloud-data/', views.get_dashboard_data, name='api-cloud-data'),
    re_path(r'^api/entradas-pie/', views.get_entradas_pie_chart_data, name='api-entradas-pie'),
    re_path(r'^api/salidas-pie/', views.get_salidas_pie_chart_data, name='api-salidas-pie'),
    re_path(r'^api/balance-line-graph/', views.get_balance_general_data, name='api-balance-line-graph'),

    ## Situaciones personales
    re_path(
        r'^situaciones-personales/(?P<habitante_id>\d+)/',
        views.SituacionesPersonalesView.as_view(),
        name='situaciones-personales'
    ),
    re_path(

ecognome/ecognome/urls.py
from django.conf.urls import re_path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Admin related URLs
    re_path(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Login related URLs
    re_path(r'^accounts/', include([
        re_path(r'^login/$', auth_views.LoginView.as_view(), name='login'),
        re_path(r'^logout/$', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
        # Password related URLs
        re_path(r'^password/', include([
            re_path(r'^change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
            re_path(r'^change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
            ])),
        ])),
    # Druids app
    re_path(r'^api/charts/', include('chartsapi.urls', namespace='chartsapi')),
    re_path(r'^', include('druids.urls', namespace='druids')),
]

ecognome/druids/models/balances.py
from decimal import Decimal as D

from django.db import models
from django.db.models import Sum
from django.db.models.functions import Coalesce

from .entradas import Entrada
from .salidas import Salida


class Balance(models.Model):
    """
    El modelo que recoge la información de un balance.
    """
    nombre = models.CharField(max_length=256)
    descripcion = models.CharField(max_length=512, verbose_name="Descripción")
    fecha_de_inicio = models.DateField()
    fecha_de_final = models.DateField()

    @property
    def entradas(self):
        return Entrada.objects.filter(
            fecha__range=[self.fecha_de_inicio, self.fecha_de_final]
        )

    @property
    def salidas(self):
        return Salida.objects.filter(
            fecha__range=[self.fecha_de_inicio, self.fecha_de_final]
        )

    @property
    def subtotal(self):
        return self.entradas.aggregate(
            subtotal=Coalesce(Sum("importe"), D("0.00"))
        )["subtotal"] - self.salidas.aggregate(
            subtotal=Coalesce(Sum("importe"), D("0.00"))
        )["subtotal"]

    def __str__(self):
        return ("%s: %s - %s" % (
            self.nombre, self.descripcion, str(self.subtotal))
        )

ecognome/druids/models/cuotas.py
from django.db import models


class CuotaMantenimiento(models.Model):
    """
    El modelo que recoge la información sobre una cuota de mantenimiento.
    """
    HABITANTE = "habitante"
    INVITADO = "invitado"
    HUESPED = "huesped"
    TIPOS_CUOTA = (
        (HABITANTE, "Habitante"),
        (INVITADO, "Invitado"),
        (HUESPED, "Huesped"),
        )
    
    importe = models.DecimalField(max_digits=4, decimal_places=2)
    tipo = models.CharField(max_length=12, choices=TIPOS_CUOTA)
    descripcion = models.CharField(max_length=512, verbose_name="Descripción")
    fecha_activacion = models.DateField()
    fecha_desactivacion = models.DateField(blank=True, null=True)
    
    def __str__(self):
        return ("%s - %s€ - %s" % (self.tipo, str(self.importe), self.descripcion))
    

class CuotaPiso(models.Model):
    """
    El modelo que recoge la información sobre una cuota de adquisición
    del derecho de uso permanente de una vivienda.
    """
    importe = models.DecimalField(max_digits=5, decimal_places=2)
    descripcion = models.CharField(max_length=512, verbose_name="Descripción")
    cuota_entrada = models.DecimalField(max_digits=5, decimal_places=2)
    cuota_onduline = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return ("%s€ - %s" % (str(self.importe), self.descripcion))

ecognome/druids/models/espacios.py
from django.db import models
from .cuotas import CuotaPiso

class Piso(models.Model):
    """
    El modelo que recoge la información sobre los diferentes pisos.
    """
    nombre = models.CharField(max_length=128)
    valor_total = models.DecimalField(max_digits=7, decimal_places=2)
    cuota_piso = models.ForeignKey(CuotaPiso, related_name='+', on_delete=models.PROTECT)

    def __str__(self):
        return self.nombre


class Trastero(models.Model):
    """
    El modelo que recoge la información sobre un trastero.
    """
    nombre = models.CharField(max_length=128)
    cuota_trastero = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.nombre

ecognome/druids/models/salidas.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.exceptions import NON_FIELD_ERRORS

from .registros import Registro


class Salida(models.Model):
    """
    El modelo que recoge la información de una salida.
    """
    CUOTA_ALQUILER_FINCA = "alquiler_compra"
    MATERIAL_REHABILITACION = "material_rehabilitacion"
    BUTANO = "butano"
    TRANSFERENCIA = "tranferencia"
    IMPUESTO = "impuesto"
    COMISION = "comision"
    INTERNET = "internet"
    AGUA = "agua"
    FIARE = "fiare"
    OTRA = "otra"

    TIPOS_SALIDA = (
        (CUOTA_ALQUILER_FINCA, "Cuota de alquiler de la finca"),
        (MATERIAL_REHABILITACION, "Material de rehabilitación"),
        (BUTANO, "Bombonas de butano"),
        (TRANSFERENCIA, "Transferencia a una cuenta nuestra"),
        (IMPUESTO, "Impuesto"),
        (COMISION, "Comisión"),
        (INTERNET, "Internet"),
        (AGUA, "Agua"),
        (FIARE, "Fiare"),
        (OTRA, "Otra Salida"),
        )
    
    fecha = models.DateField()
    importe = models.DecimalField(max_digits=7, decimal_places=2)
    tipo_salida = models.CharField(max_length=128, choices=TIPOS_SALIDA, verbose_name="Tipo de Salida")
    comentarios = models.CharField(max_length=512, blank=True, null=True)
    usuaria_economia = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Usuaria de economía")
    registro = models.ForeignKey(Registro, on_delete=models.PROTECT)

    def validate_unique(self, *args, **kwargs):
        super(Salida, self).validate_unique(*args, **kwargs)
        if not self.id:
            if self.__class__.objects.filter(importe=self.importe,
                                             fecha=self.fecha,
                                             tipo_salida=self.tipo_salida,
                                             registro=self.registro).exists():
                raise ValidationError(
                    {
                        NON_FIELD_ERRORS: [
                            "Alguien se te ha adelantado y ya ha insertado esta entrada",
                            ],
                    }
                )

    def __str__(self):
        return self.tipo_salida

ecognome/druids/forms.py
from django import forms
from druids.models import Habitante, ProyectoProductivo, Entrada, Salida


class SelectHabitanteForm(forms.Form):
    """
    Just a single select field with all the habitants.
    """
    habitante = forms.ModelChoiceField(required=True, label="Escoge un habitante",
                                       queryset=Habitante.objects.all().order_by("nombre"))


class SelectProyectoProductivoForm(forms.Form):
    """
    Just a single select field with all projects.
    """
    proyecto = forms.ModelChoiceField(required=True, label="Escoge un proyecto",
                                      queryset=ProyectoProductivo.objects.all().order_by("nombre"))


class SelectEntradaTipoForm(forms.Form):
    """
    Just a single select field with all kind of incomes
    """
    tipo_entrada = forms.ChoiceField(required=True, label="Escoge un tipo de entrada",
                                     choices=Entrada.TIPOS_ENTRADA)


class SelectSalidaTipoForm(forms.Form):
    """
    Just a single select field with all kind of outcomes
    """
    tipo_salida = forms.ChoiceField(required=True, label="Escoge un tipo de salida",
                                    choices=Salida.TIPOS_SALIDA)

ecognome/druids/templates/druids/registros/crear_registro.html
{% extends "druids.html" %}
{% load druids_tags %}

{% block title %} Eco-gnomy: {{ view.title }} {% endblock title %}

{% block content %}
<div class="row">
  <div class="medium-6 large-6 columns medium-centered large-centered">
    <div class="panel">
      <h2>{{ view.title }}</h2>
      <br />
      <br />
      <form method="post">
	{% csrf_token %}
	{% non_field_errors form %}
	{% form_field form.nombre %}
	<button type="submit" class="expand radius button">Crear</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

ecognome/druids/templates/druids/registros/extracto-registro.html
{% extends 'druids.html' %}
{% load druids_tags %}
{% load staticfiles %}

{% block title %}Eco-gnomy: {{ view.title }}{% endblock title %}

{% block content %}
<div class="row">
  <div class="medium-12 large-12 columns medium-centered large-centered">
    <div class="panel">
      <h2>{{ view.title }}</h2>
      <table style="width:100%" id="movimientos">
	<thead>
	  <tr>
	    <th>Linea</th>
	    <th>Fecha</th>
	    <th>Tipo</th>
	    <th>Comentarios</th>
	    <th>Relación</th>
	    <th>Usuaria economia</th>
	    <th>Importe</th>
	    <th>Subtotal</th>
	    <th>Rectificar</th>
	  </tr>
	</thead>
	<tbody>
	  {% for linea in lineas|dictsortreversed:"numero" %}
	  <tr>
	    <td>{{ linea.numero }}</td>
	    <td>{{ linea.movimiento.fecha }}</td>
	    <td>{% if linea.movimiento.tipo %}{{ linea.movimiento.get_tipo_display }}{% elif linea.movimiento.tipo_salida %}{{ linea.movimiento.get_tipo_salida_display }}{% endif %}</td>
	    <td>{{ linea.movimiento.comentarios }}</td>
	    <td>{% if linea.movimiento.entradamantenimiento %}{{ linea.movimiento.entradamantenimiento.persona }}
	      {% elif linea.movimiento.entradaalquiler %}{{ linea.movimiento.entradaalquiler.persona }}
	      {% elif linea.movimiento.entradapiso %}{{ linea.movimiento.entradapiso.habitante_piso }}
	      {% elif linea.movimiento.entradadonativo %}{{ linea.movimiento.entradadonativo.persona }}
	      {% elif linea.movimiento.entradaespacioproyectoproductivo %}{{ linea.movimiento.entradaespacioproyectoproductivo.proyecto_productivo }}
	      {% elif linea.movimiento.entradabeneficioproyectoproductivo %}{{ linea.movimiento.entradabeneficioproyectoproductivo.proyecto_productivo }}
	      {% elif linea.movimiento.entradaalquilertrastero %}{{ linea.movimiento.entradaalquilertrastero.persona_trastero }}
	      {% else %}---{% endif %}</td>
	    <td>{{ linea.movimiento.usuaria_economia }}</td>
	    <td id="importe-{{ linea.numero }}" {% with clase=linea.movimiento|to_class_name %}{% if clase == "Entrada" %}style="color:green;"{% else %}style="color:red;"{% endif %}{% endwith %}>{{ linea.movimiento.importe }}</td>
	    <td id="subtotal-{{ linea.numero }}"></td>
	    <td>{% with clase=linea.movimiento|to_class_name %}{% if clase == "Salida" %}<a href="{% url 'druids:rectificar-salida' salida_id=linea.movimiento.id %}"><center>X</center></a>{% else %}<a href="{% url 'druids:rectificar-entrada' entrada_id=linea.movimiento.id %}"><center>X</center></a>{% endif %}{% endwith %}</td>
	  </tr>
	  {% empty %}
	  <tr>
	    <td>No hay ningúna entrada para estas fechas.</td>
	  </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

{% block body_js %}
<script src="{% static 'druids/js/vendor/decimal.min.js' %}"></script>
<script>
  {% for linea in lineas|dictsortreversed:"numero" %}
  {% if forloop.first %}
  $("#subtotal-{{ linea.numero }}").html("{{ linea.movimiento.registro.saldo }}");
  {% else %}
  var linea_id = {{ linea.numero }} + 1;
  var old_subtotal = new Decimal($("#subtotal-"+linea_id).html());
  var difference = new Decimal($("#importe-"+linea_id).html());
  var new_subtotal = {% with vieja_linea=lineas|dictsortreversed:"numero"|previous_line_in_list:linea %}{% with clase=vieja_linea.movimiento|to_class_name %}{% if clase == "Entrada" %} old_subtotal.minus(difference){% elif clase == "Salida" %} old_subtotal.plus(difference){% endif %}{% endwith %}{% endwith %};
  $("#subtotal-{{ linea.numero }}").html(new_subtotal.toFixed(2));
  {% endif %}
  {% endfor %}
</script>
{% endblock body_js %}

ecognome/druids/templates/druids/registros/lista-registros.html
{% extends 'druids.html' %}

{% block title %}Eco-gnomy: {{ view.title }}{% endblock title %}

{% block content %}
<div class="row">
  <div class="medium-6 large-6 columns medium-centered large-centered">
    <div class="panel">
      <h2>{{ view.title }}</h2>
      <br />
      <br />
      <table>
	<thead>
	  <tr>
	    <th>Nombre</th>
	    <th>Saldo</th>
	    <th>Extracto</th>
	  </tr>
	</thead>
	<tbody>
	  {% for registro in registros %}
	  <tr>
	    <td>{{ registro.nombre }}</td>
	    <td>{{ registro.saldo }}</td>
	    <td>
	      <a href="{% url 'druids:extracto-registro' registro.registro_ptr.id %}">
		Ver
	      </a>
	    </td>
	  </tr>
	  {% empty %}
	  <tr>
	    <td>No hay ningún registro creado.</td>
	  </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}