ecognome/druids/urls.py
from django.conf.urls import re_path

from . import views

app_name = 'druids'
urlpatterns = [

    # GT economia

    ## Estadísticas

    re_path(
        r'^gt-economia/estadisticas/reportes_mensuales_por_tipo/(?P<pk>\d+)/',
        views.ReporteMensualPorTipoDetailView.as_view(),
        name="reporte-mensual-por-tipo",
    ),

    re_path(
        r'^gt-economia/estadisticas/reportes_mensuales_por_tipo/',
        views.reportes_mensuales_por_tipo,
        name="reportes-mensuales-por-tipo",
    ),
    
    ## Cuotas
    re_path(r'^gt-economia/cuotas/mantenimiento/crear/',
        views.CuotaMantenimientoCreateView.as_view(),
        name="crear-mantenimiento"
        ),
    re_path(
        r'^gt-economia/cuotas/mantenimiento/(?P<pk>\d+)/',
        views.CuotaMantenimientoUpdateView.as_view(),
        name="desactivar-mantenimiento",
    ),
    re_path(r'^gt-economia/cuotas/mantenimiento/',
        views.CuotaMantenimientoListView.as_view(),
        name="lista-mantenimiento"
        ),
    re_path(r'^gt-economia/cuotas/piso/crear/',
        views.CuotaPisoCreateView.as_view(),
        name="crear-cuota-piso"
        ),
    re_path(r'^gt-economia/cuotas/piso/',
        views.CuotaPisoListView.as_view(),
        name="lista-cuotas-piso"
        ),
    
    ## Espacios
    re_path(r'^gt-economia/espacios/pisos/crear/',
        views.PisoCreateView.as_view(),
        name="crear-piso"
        ),
    re_path(r'^gt-economia/espacios/pisos/(?P<pk>\d+)/',
        views.PisoUpdateView.as_view(),
        name="editar-piso"
        ),
    re_path(r'^gt-economia/espacios/pisos/',
        views.PisoListView.as_view(),
        name="lista-pisos"
        ),
    re_path(r'^gt-economia/espacios/trasteros/crear/',
        views.TrasteroCreateView.as_view(),
        name="crear-trastero"
        ),
    re_path(r'^gt-economia/espacios/trasteros/(?P<pk>\d+)/',
        views.TrasteroUpdateView.as_view(),
        name="editar-trastero"
        ),
    re_path(r'^gt-economia/espacios/trasteros/',
        views.TrasteroListView.as_view(),
        name="lista-trasteros"
        ),

    ## Cuadernos Contables
    re_path(r'^gt-economia/cuadernos/entradas/(?P<tipo_entrada>\w+)',
        views.cuaderno_contable_entradas,
        name="cuaderno_contable_entradas",
        ),
    re_path(r'^gt-economia/cuadernos/entradas',
        views.cuaderno_contable_entradas,
        name="cuaderno_contable_entradas",
        ),
    re_path(r'^gt-economia/cuadernos/salidas/(?P<tipo_salida>\w+)',
        views.cuaderno_contable_salidas,
        name="cuaderno_contable_salidas",
        ),
    re_path(r'^gt-economia/cuadernos/salidas',
        views.cuaderno_contable_salidas,
        name="cuaderno_contable_salidas",
        ),
    
    ## Registros
    re_path(r'^gt-economia/registros/metalico/crear/',
        views.MetalicoCreateView.as_view(),
        name="crear-metalico"
        ),
    re_path(r'^gt-economia/registros/metalico/',
        views.MetalicoListView.as_view(),
        name="lista-metalicos"
        ),
    re_path(r'^gt-economia/registros/banco/crear/',
        views.BancoCreateView.as_view(),
        name="crear-banco"
        ),
    re_path(r'^gt-economia/registros/banco/',
        views.BancoListView.as_view(),
        name="lista-bancos"
        ),
    re_path(r'^gt-economia/registros/electronico/crear/',
        views.PaypalCreateView.as_view(),
        name="crear-paypal"
        ),
    re_path(r'^gt-economia/registros/electronico/',
        views.PaypalListView.as_view(),
        name="lista-paypals"
        ),
    re_path(r'^gt-economia/registros/extracto/(?P<registro_id>\d+)/',
        views.extracto_registro,
        name="extracto-registro"
        ),
    re_path(r'^gt-economia/registros/extracto/rectificar_salida/(?P<salida_id>\d+)/',
        views.rectificar_salida,
        name="rectificar-salida"
        ),
    re_path(r'^gt-economia/registros/extracto/rectificar_entrada/(?P<entrada_id>\d+)/',
        views.rectificar_entrada,
        name="rectificar-entrada"
        ),
    
    ## Proyectos
    re_path(r'^gt-economia/proyectos/crear/',
        views.ProyectoProductivoCreateView.as_view(),
        name="crear-proyecto"
        ),
    re_path(r'^gt-economia/proyectos/(?P<pk>\d+)/',
        views.ProyectoProductivoUpdateView.as_view(),
        name="editar-proyecto"
        ),
    re_path(r'^gt-economia/proyectos/',
        views.ProyectoProductivoListView.as_view(),
        name="lista-proyectos"
        ),

    ## Personas
    re_path(r'^gt-economia/personas/habitantes/crear/',
        views.HabitanteCreateView.as_view(),
        name="crear-habitante"
        ),
    re_path(r'^gt-economia/personas/habitantes/(?P<pk>\d+)/',
        views.HabitanteUpdateView.as_view(),
        name="editar-habitante"
        ),
    re_path(r'^gt-economia/personas/habitantes/',
        views.HabitanteListView.as_view(),
        name="lista-habitantes"
        ),
    re_path(r'^gt-economia/personas/invitadas/crear/',
        views.InvitadaCreateView.as_view(),
        name="crear-invitada"
        ),
    re_path(r'^gt-economia/personas/invitadas/(?P<pk>\d+)/',
        views.InvitadaUpdateView.as_view(),
        name="editar-invitada"
        ),
    re_path(r'^gt-economia/personas/invitadas/',
        views.InvitadaListView.as_view(),
        name="lista-invitadas"
        ),
    re_path(r'^gt-economia/personas/huespedes/crear/',
        views.HuespedCreateView.as_view(),
        name="crear-huesped"
        ),
    re_path(r'^gt-economia/personas/huespedes/(?P<pk>\d+)/',
        views.HuespedUpdateView.as_view(),
        name="editar-huesped"
        ),
    re_path(r'^gt-economia/personas/huespedes/',
        views.HuespedListView.as_view(),
        name="lista-huespedes"
        ),

    ## Pactos
    re_path(r'^gt-economia/pactos/habitantepiso/crear/',
        views.HabitantePisoCreateView.as_view(),
        name="crear-habitantepiso"
        ),
    re_path(r'^gt-economia/pactos/habitantepiso/(?P<pk>\d+)/',
        views.HabitantePisoUpdateView.as_view(),
        name="editar-habitantepiso"
        ),
    re_path(r'^gt-economia/pactos/habitantepiso/',
        views.HabitantePisoListView.as_view(),
        name="lista-habitantepiso"
        ),
    re_path(r'^gt-economia/pactos/personatrastero/crear/',
        views.PersonaTrasteroCreateView.as_view(),
        name="crear-personatrastero"
        ),
    re_path(r'^gt-economia/pactos/personatrastero/(?P<pk>\d+)/',
        views.PersonaTrasteroUpdateView.as_view(),
        name="editar-personatrastero"
        ),
    re_path(r'^gt-economia/pactos/personatrastero/',
        views.PersonaTrasteroListView.as_view(),
        name="lista-personatrastero"
        ),

    ## Movimientos
    re_path(r'^gt-economia/movimientos/salidas/crear/',
        views.insertar_salidas,
        name="crear-salida"
        ),
    re_path(r'^gt-economia/movimientos/entradas/otras/crear/',
        views.insertar_entradas_otras,
        name="crear-otras-entradas"
        ),
    re_path(r'^gt-economia/movimientos/entradas/alquileres/crear/',
        views.insertar_entradas_alquileres,
        name="crear-alquileres-entradas"
        ),
    re_path(r'^gt-economia/movimientos/entradas/proyectos/crear/',
        views.insertar_entradas_proyectos,
        name="crear-proyectos-entradas"
        ),

    ## Balances
    re_path(r'^gt-economia/balances/crear/',
        views.BalanceCreateView.as_view(),
        name="crear-balance"
        ),
    re_path(r'^gt-economia/balances/(?P<pk>\d+)/',
        views.BalanceDetailView.as_view(),
        name="ver-balance"
        ),
    re_path(r'^gt-economia/balances/',
        views.BalanceListView.as_view(),
        name="lista-balances"
        ),

    ## Export CSV

    re_path(r'^gt-economia/csv/entradas/$',
        views.exportar_entradas_csv,
        name="exportar_entradas_csv",
        ),
    re_path(r'^gt-economia/csv/salidas/$',
        views.exportar_salidas_csv,
        name="exportar_salidas_csv",
        ),
    re_path(r'^gt-economia/csv/pisos/$',
        views.exportar_pisos_csv,
        name="exportar_pisos_csv",
        ),
    re_path(r'^gt-economia/csv/trasteros/$',
        views.exportar_trasteros_csv,
        name="exportar_trasteros_csv",
        ),
    re_path(r'^gt-economia/csv/cuotas_piso/$',
        views.exportar_cuotas_piso_csv,
        name="exportar_cuotas_piso_csv",
        ),
    re_path(r'^gt-economia/csv/cuotas_mantenimiento/$',
        views.exportar_cuotas_mantenimiento_csv,
        name="exportar_cuotas_mantenimiento_csv",
        ),
    re_path(r'^gt-economia/csv/habitante_piso/$',
        views.exportar_habitante_piso_csv,
        name="exportar_habitante_piso_csv",
        ),
    re_path(r'^gt-economia/csv/persona_trastero/$',
        views.exportar_persona_trastero_csv,
        name="exportar_persona_trastero_csv",
        ),
    re_path(r'^gt-economia/csv/personas/$',
        views.exportar_personas_csv,
        name="exportar_personas_csv",
        ),
    re_path(r'^gt-economia/csv/registros/$',
        views.exportar_registros_csv,
        name="exportar_registros_csv",
        ),
    re_path(r'^gt-economia/csv/proyectos/$',
        views.exportar_proyectos_csv,
        name="exportar_proyectos_csv",
        ),
    
    ## Dashboard
    re_path(r'^gt-economia/', views.gt_dashboard, name='gt-dashboard'),

    # Public dashboard
    ## API
    re_path(r'^api/cloud-data/', views.get_dashboard_data, name='api-cloud-data'),
    re_path(r'^api/entradas-pie/', views.get_entradas_pie_chart_data, name='api-entradas-pie'),
    re_path(r'^api/salidas-pie/', views.get_salidas_pie_chart_data, name='api-salidas-pie'),
    re_path(r'^api/balance-line-graph/', views.get_balance_general_data, name='api-balance-line-graph'),

    ## Situaciones personales
    re_path(
        r'^situaciones-personales/(?P<habitante_id>\d+)/',
        views.SituacionesPersonalesView.as_view(),
        name='situaciones-personales'
    ),
    re_path(

ecognome/ecognome/urls.py
from django.conf.urls import re_path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Admin related URLs
    re_path(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Login related URLs
    re_path(r'^accounts/', include([
        re_path(r'^login/$', auth_views.LoginView.as_view(), name='login'),
        re_path(r'^logout/$', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
        # Password related URLs
        re_path(r'^password/', include([
            re_path(r'^change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
            re_path(r'^change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
            ])),
        ])),
    # Druids app
    re_path(r'^api/charts/', include('chartsapi.urls', namespace='chartsapi')),
    re_path(r'^', include('druids.urls', namespace='druids')),
]

ecognome/druids/models/balances.py
from decimal import Decimal as D

from django.db import models
from django.db.models import Sum
from django.db.models.functions import Coalesce

from .entradas import Entrada
from .salidas import Salida


class Balance(models.Model):
    """
    El modelo que recoge la información de un balance.
    """
    nombre = models.CharField(max_length=256)
    descripcion = models.CharField(max_length=512, verbose_name="Descripción")
    fecha_de_inicio = models.DateField()
    fecha_de_final = models.DateField()

    @property
    def entradas(self):
        return Entrada.objects.filter(
            fecha__range=[self.fecha_de_inicio, self.fecha_de_final]
        )

    @property
    def salidas(self):
        return Salida.objects.filter(
            fecha__range=[self.fecha_de_inicio, self.fecha_de_final]
        )

    @property
    def subtotal(self):
        return self.entradas.aggregate(
            subtotal=Coalesce(Sum("importe"), D("0.00"))
        )["subtotal"] - self.salidas.aggregate(
            subtotal=Coalesce(Sum("importe"), D("0.00"))
        )["subtotal"]

    def __str__(self):
        return ("%s: %s - %s" % (
            self.nombre, self.descripcion, str(self.subtotal))
        )

ecognome/druids/models/cuotas.py
from django.db import models


class CuotaMantenimiento(models.Model):
    """
    El modelo que recoge la información sobre una cuota de mantenimiento.
    """
    HABITANTE = "habitante"
    INVITADO = "invitado"
    HUESPED = "huesped"
    TIPOS_CUOTA = (
        (HABITANTE, "Habitante"),
        (INVITADO, "Invitado"),
        (HUESPED, "Huesped"),
        )
    
    importe = models.DecimalField(max_digits=4, decimal_places=2)
    tipo = models.CharField(max_length=12, choices=TIPOS_CUOTA)
    descripcion = models.CharField(max_length=512, verbose_name="Descripción")
    fecha_activacion = models.DateField()
    fecha_desactivacion = models.DateField(blank=True, null=True)
    
    def __str__(self):
        return ("%s - %s€ - %s" % (self.tipo, str(self.importe), self.descripcion))
    

class CuotaPiso(models.Model):
    """
    El modelo que recoge la información sobre una cuota de adquisición
    del derecho de uso permanente de una vivienda.
    """
    importe = models.DecimalField(max_digits=5, decimal_places=2)
    descripcion = models.CharField(max_length=512, verbose_name="Descripción")
    cuota_entrada = models.DecimalField(max_digits=5, decimal_places=2)
    cuota_onduline = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return ("%s€ - %s" % (str(self.importe), self.descripcion))

ecognome/druids/models/espacios.py
from django.db import models
from .cuotas import CuotaPiso

class Piso(models.Model):
    """
    El modelo que recoge la información sobre los diferentes pisos.
    """
    nombre = models.CharField(max_length=128)
    valor_total = models.DecimalField(max_digits=7, decimal_places=2)
    cuota_piso = models.ForeignKey(CuotaPiso, related_name='+', on_delete=models.PROTECT)

    def __str__(self):
        return self.nombre


class Trastero(models.Model):
    """
    El modelo que recoge la información sobre un trastero.
    """
    nombre = models.CharField(max_length=128)
    cuota_trastero = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.nombre

ecognome/druids/models/registros.py
from decimal import Decimal as D

from django.db import models
from django.db.models import Sum
from django.db.models.functions import Coalesce


class Registro(models.Model):
    """
    Clase genérica para los difertes registros contables:
    """
    nombre = models.CharField(max_length=32)

    @property
    def saldo(self):
        return self.entrada_set.aggregate(
            subtotal=Coalesce(Sum("importe"), D("0.00")),
        )["subtotal"] - self.salida_set.aggregate(
            subtotal=Coalesce(Sum("importe"), D("0.00")),
        )["subtotal"]

    def __str__(self):
        return self.nombre


class Metalico(Registro):
    """
    El modelo que recoge la información del registro de
    movimientos en metálico.
    """
    class Meta:
        verbose_name = "Metálico"


class Banco(Registro):
    """
    El modelo que recoge la información del registro de
    un banco.
    """
    class Meta:
        verbose_name = "Banco"


class PayPal(Registro):
    """
    El modelo que recoge la información del registro de
    una cuenta de PayPal.
    """
    class Meta:
        verbose_name = "PayPal"

ecognome/druids/forms.py
from django import forms
from druids.models import Habitante, ProyectoProductivo, Entrada, Salida


class SelectHabitanteForm(forms.Form):
    """
    Just a single select field with all the habitants.
    """
    habitante = forms.ModelChoiceField(required=True, label="Escoge un habitante",
                                       queryset=Habitante.objects.all().order_by("nombre"))


class SelectProyectoProductivoForm(forms.Form):
    """
    Just a single select field with all projects.
    """
    proyecto = forms.ModelChoiceField(required=True, label="Escoge un proyecto",
                                      queryset=ProyectoProductivo.objects.all().order_by("nombre"))


class SelectEntradaTipoForm(forms.Form):
    """
    Just a single select field with all kind of incomes
    """
    tipo_entrada = forms.ChoiceField(required=True, label="Escoge un tipo de entrada",
                                     choices=Entrada.TIPOS_ENTRADA)


class SelectSalidaTipoForm(forms.Form):
    """
    Just a single select field with all kind of outcomes
    """
    tipo_salida = forms.ChoiceField(required=True, label="Escoge un tipo de salida",
                                    choices=Salida.TIPOS_SALIDA)

ecognome/templates/_breadcrumbs.html
{% if breadcrumbs %}
<ol class="breadcrumb">
  {% for breadcrumb in breadcrumbs %}
  {% if not breadcrumb.is_active %}
  <li class="breadcrumb-item">
    <a href="{{ breadcrumb.url }}">{{ breadcrumb.title }}</a>
  </li>
  {% else %}
  <li class="breadcrumb-item active">{{ breadcrumb.title }}</li>
  {% endif %}
  {% endfor %}
</ol>
{% endif %}

ecognome/templates/_footer.html
<footer class="sticky-footer">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>No F****ng Copyright © Calafou - Ecognomy</span>
    </div>
  </div>
</footer>

ecognome/templates/_navbar.html
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

  <a class="navbar-brand mr-1" href="index.html">Calafou - Ecognomy</a>

  <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
    <i class="fas fa-bars"></i>
  </button>

  <!-- Navbar -->
  {% comment %}
  <ul class="navbar-nav ml-auto mr-md-0">
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle fa-fw"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">Settings</a>
        <a class="dropdown-item" href="#">Activity Log</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
      </div>
    </li>
  </ul>
  {% endcomment %}
</nav>

ecognome/templates/_sidebar.html
<ul class="sidebar navbar-nav">
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'druids:index' %}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Vista Aérea</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'druids:situaciones-personales' %}">
      <i class="fas fa-fw fa-child"></i>
      <span>Situaciones Personales</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'druids:proyectos-productivos' %}">
      <i class="fas fa-fw fa-gavel"></i>
      <span>Proyectos Productivos</span>
    </a>
  </li>
  {% comment %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-fw fa-folder"></i>
      <span>Pages</span>
    </a>
    <div class="dropdown-menu" aria-labelledby="pagesDropdown">
      <h6 class="dropdown-header">Login Screens:</h6>
      <a class="dropdown-item" href="login.html">Login</a>
      <a class="dropdown-item" href="register.html">Register</a>
      <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
      <div class="dropdown-divider"></div>
      <h6 class="dropdown-header">Other Pages:</h6>
      <a class="dropdown-item" href="404.html">404 Page</a>
      <a class="dropdown-item" href="blank.html">Blank Page</a>
    </div>
  </li>
  {% endcomment %}
  <li class="nav-item">
    <a class="nav-link" href="#">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Gráficos</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="tables.html">
      <i class="fas fa-fw fa-table"></i>
      <span>Planillas</span></a>
  </li>
</ul>

ecognome/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Ecognomy">
    <meta name="author" content="Calafou">
    {% block meta %}{% endblock meta %}

    <title>Calafou - {% block title %}Ecognomy{% endblock title %}</title>

    <!-- Bootstrap core CSS-->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static "vendor/datatables/dataTables.bootstrap4.css" %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static "css/sb-admin.css" %}" rel="stylesheet">

    <link href="{% static "vendor/datepicker/css/default.picker.css" %}" rel="stylesheet"/>
    <link href="{% static "vendor/datepicker/css/default.picker.date.css" %}" rel="stylesheet"/>

    {# Custom CSS #}
    {% block css %}
    {% endblock css %}

    {# Custom head JS #}
    {% block head_js %}{% endblock head_js %}
  </head>
  <body id="page-top">

    {% include "_navbar.html" %}

    <div id="wrapper">

      {% include "_sidebar.html" %}

      <div id="content-wrapper">
	<div class="container-fluid">

	  {% include "_breadcrumbs.html" %}

	  {# Main content goes here #}
	  {% block base_body %}{% endblock base_body %}

	</div>

	{% include "_footer.html" %}

      </div>
    </div>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

    <!-- Page level plugin JavaScript-->
    <script src="{% static "vendor/chart.js/Chart.min.js" %}"></script>
    <script src="{% static "vendor/datatables/jquery.dataTables.js" %}"></script>
    <script src="{% static "vendor/datatables/dataTables.bootstrap4.js" %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static "js/sb-admin.min.js" %}"></script>

    <!-- Custom date picker -->
    <script src="{% static "vendor/datepicker/js/picker.js" %}"></script>
    <script src="{% static "vendor/datepicker/js/picker.date.js" %}"></script>
    <script>
      $('.date-picker-0').pickadate({'format': 'yyyy-mm-dd'});
    </script>

    {# Custom JS #}
    {% block body_js %}
    {% endblock body_js %}
  </body>
</html>

ecognome/templates/druids.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{% endblock title %}

{% block css %}
<link href="{% static "foundation/css/foundation-icons.css" %}" rel="stylesheet"/>
<style>
  .messages {
  .alert-box {
  border-radius: $global-radius;
  margin: $half-padding 0 $half-padding;
  box-shadow: 0px 3px 2px rgba(0, 0, 0, 0.2);
  border-top: 0;
  padding-top: $half-padding;
  padding-bottom: $half-padding;
  }
}
</style>
{% endblock css %}

{% block base_body %}
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="{% url 'druids:index' %}">Home</a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
      <a href="#">{% if user.is_authenticated %}{{ user.name }}{% else %}Eco-gnomy{% endif %}</a>
	<ul class="dropdown">
	  {% if not user.is_authenticated %}
	  <li class="active">
	    <a href="{% url 'login' %}"><i class="fi-arrow-up size-12"></i> Log in</a>
	  </li>
	  {% else %}
	  <li>
	    <a href="{% url 'druids:gt-dashboard' %}"><i class="fi-home size-12"></i> Panel GT</a>
	  </li>
	  <li class="active">
	    <a href="{% url 'logout' %}"><i class="fi-arrow-down size-12"></i> Log out</a>
	  </li>
	  {% endif %}
	</ul>
      </li>
    </ul>
    <!-- Lefat Nav Section -->
    <ul class="left">
      <li>
	<a href="{% url 'druids:situaciones-personales' %}">Situaciones personales</a>
      </li>
      <li>
	<a href="{% url 'druids:balance-general' %}">Balance general</a>
      </li>
      <li>
	<a href="{% url 'druids:proyectos-productivos' %}">Proyectos productivos</a>
      </li>
   <!--    <li>
	 <a href="#">Cuenta atrás</a>
      </li>-->
    </ul>
  </section>
</nav>
{% if messages %}
<div class="row messages">
  {% for message in messages %}
  <div data-alert class="alert-box radius {% if message.tags %}{{ message.tags }}{% endif %}">
    {% if 'info' in message.tags %}<i class="fi-info size-36"></i>{% endif %}
    {% if 'success' in message.tags %}<i class="fi-star size-36"></i>{% endif %}
    {% if 'warning' in message.tags %}<i class="fi-alert size-36"></i>{% endif %}
    {% if 'alert' in message.tags %}<i class="fi-skull size-36"></i>{% endif %}
    {{ message }}
    <a href="#" class="close">&times;</a>
  </div>
  {% endfor %}
</div>
{% endif %}

<br />

{% block content %}
{% endblock content %}
{% endblock base_body %}